const mapData: {
  type: "FeatureCollection";
  name: string;
  features: {
    type: "Feature";
    properties: {
      featurecla: "Admin-1 scale rank";
      scalerank: 3;
      adm1_code: "ITA-5442";
      diss_me: 5442;
      iso_3166_2: "IT-AO";
      wikipedia: null;
      iso_a2: "IT";
      adm0_sr: 1;
      name: "Aoste";
      name_alt: "Aosta|Aosta Valley|Val d'Aoste|Vallée d'Aoste";
      name_local: null;
      type: "Province";
      type_en: "Province";
      code_local: "11";
      code_hasc: "IT.AO";
      note: "ITC";
      hasc_maybe: null;
      region: string;
      region_cod: "IT-23";
      provnum_ne: 12;
      gadm_level: 1;
      check_me: 20;
      datarank: 3;
      abbrev: null;
      postal: "AO";
      area_sqkm: 0;
      sameascity: null;
      labelrank: 3;
      name_len: 5;
      mapcolor9: 8;
      mapcolor13: 7;
      fips: "IT19";
      fips_alt: null;
      woe_id: 12591856;
      woe_label: null;
      woe_name: "Aosta";
      latitude: 45.7126;
      longitude: 7.35059;
      sov_a3: "ITA";
      adm0_a3: "ITA";
      adm0_label: 2;
      admin: "Italy";
      geonunit: "Italy";
      gu_a3: "ITA";
      gn_id: 3182996;
      gn_name: "Provincia di Aosta";
      gns_id: -110503;
      gns_name: "Valle d'Aosta, Provincia di";
      gn_level: 2;
      gn_region: null;
      gn_a1_code: "IT.AO";
      region_sub: null;
      sub_code: null;
      gns_level: 2;
      gns_lang: null;
      gns_adm1: null;
      gns_region: "IT19";
      min_label: 9;
      max_label: 11;
      min_zoom: 9;
      wikidataid: "Q3367";
      name_ar: null;
      name_bn: null;
      name_de: "Aosta";
      name_en: string;
      name_es: "Aosta";
      name_fr: "Aoste";
      name_el: null;
      name_hi: null;
      name_hu: "Aosta";
      name_id: "Aosta";
      name_it: "Aosta";
      name_ja: null;
      name_ko: null;
      name_nl: "Aosta";
      name_pl: "Aosta";
      name_pt: "Aosta";
      name_ru: null;
      name_sv: "Aosta";
      name_tr: "Aosta";
      name_vi: "Aosta";
      name_zh: null;
      ne_id: "1159310915";
    };
    geometry: {
      type: "MultiPolygon";
      coordinates: [[[number, number][]]];
    };
  }[];
};

export default mapData;
